import React from "react";
import Script from "next/script";

const contact = () => {
  return (
    
    <div className="h-screen bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-500 flex items-center justify-center text-white text-center">
      
        <Script>{`alert("Welcome to contact Page")`}</Script>
        <div>
        <h2 className="text-5xl font-bold mb-4">Welcome to MyNextSite</h2>
        
        
        <p className="text-xl">Phone No. 7498300546</p>
        <p className="text-xl">Email Id : ompotdar7498@gmail.com</p>
      </div>
    </div>
  );
};

export default contact;


export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};